export const workExperience = [
  {
    company: "San Francisco Museum of Modern Art",
    role: "Software Engineer - Full Stack",
    startDate: "2023-09-01",
    endDate: "2025-05-01",
    description: [
      "Built ticketing platform features (ASP.NET, JavaScript, HTML/SCSS) integrating with Tessitura CRM APIs; maintained existing architecture while adding new functionality",
      "Led WCAG 2.1 AA compliance sprint: zero critical defects in pre-audit QA across entire platform",
      "Supported front end through major infrastructure upgrades (.NET Core, CRM migrations) with minimal disruption",
      "Introduced Jest testing for JavaScript components and readied it for CI/CD pipeline",
    ],
    location: "San Francisco, CA",
    logo: "/images/logos/sfmoma.png",
  },
  {
    company: "Intrinsic (Alphabet/Google X)",
    role: "UI/UX Developer (Contract)",
    startDate: "2023-01-01",
    endDate: "2023-05-01",
    description: [
      "Built production Angular/TypeScript components in Google's monorepo (Piper/Bazel) consuming internal APIs",
      "Delivered scalable UI features through automated builds and multi-stage testing in cloud infrastructure",
      "Translated Figma designs to functional interfaces; maintained 100% test coverage standards in large-scale environment",
      "Collaborated with engineering teams on API integration requirements; communicated technical constraints and solutions",
    ],
    location: "Mountain View, CA",
    logo: "/images/logos/google.png",
  },
  {
    company: "Jefferson Health",
    role: "Software Engineer - Front End (Contract)",
    startDate: "2021-11-01",
    endDate: "2023-01-01",
    description: [
      "Built React/TypeScript/Next.js IT support ticket routing tool; improved support ticket response times 3X",
      "Modernized entire Shopify development workflow: migrated to GitHub integration with protected branches, Shopify CLI for local dev, and automatic deployments—creating a proper dev-to-test-to-prod pipeline; trained the team on new practices",
      "Migrated Shopify 1.x to 2.0: converted all Liquid templates to JSON schema, doubling admin panel speed",
      "Reduced storefront load time ~25% through performance optimization (code-splitting, lazy loading, deferral)",
    ],
    location: "Philadelphia, PA",
    logo: "/images/logos/jefferson.png",
  },
  {
    company: "Dental Game Plan",
    role: "Software Engineer - Front End",
    startDate: "2021-04-01",
    endDate: "2021-12-01",
    description: [
      "Regularly shipped React/TypeScript/Next.js landing pages for various clients during tenure",
      "Shipped 6 Jekyll Static Site Generator sites for healthcare clients; updated and optimized existing client sites",
      "Extended custom SSG framework architecture; reduced developer time 50% for future site launches",
    ],
    location: "Remote",
    logo: "/images/logos/dentalgameplan.png",
  },
  {
    company: "Kul Inc.",
    role: "Software Engineer - Front End",
    startDate: "2020-05-01",
    endDate: "2021-03-01",
    description: [
      "Second technical hire; owned entire Shopify storefront (Hydrogen/React, Liquid, JS) while company explored multiple revenue models",
      "Led a full rebranding and migration over 3 weeks, with zero downtime, during a strategic pivot",
      "Built front end for rewards system with data visualization and charts (c3.js, d3.js, Three.js)",
      "Experienced startup reality: rapid experimentation, trying multiple business models, competing priorities and rapid strategy shifts",
      "Optimized performance of the storefront, cutting load times by ~18% (code-splitting, lazy loading, deferral)",
    ],
    location: "San Francisco, CA",
    logo: "/images/logos/kul.png",
  },
  {
    company: "Marathon Products",
    role: "Manager",
    startDate: "2015-01-01",
    endDate: "2020-01-01",
    description: [
      "Managed production team, improved efficiency 15%, reduced processing errors 10%",
      "Implemented Help Desk system: ~50% faster response, zero lost tickets after launch",
      "Spearheaded Bug Tracking system adoption, increasing bug fix speed by 25%",
      "Achieved 30% fewer support tickets and a 75% drop in repetitive issues through documentation overhaul",
      "Administered and streamlined ISO 9001 compliance program",
      "Process improvements listed above saved company 100+ hours annually",
      "Transitioned to software engineering for continuous technical challenges",
    ],
    location: "San Francisco, CA",
    logo: "/images/logos/marathon.png",
  },
];
